// <auto-generated />
using System;
using K2TeamProjectNEW.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace K2TeamProjectNEW.Migrations.K2TeamProjectCodeFirstDb
{
    [DbContext(typeof(K2TeamProjectCodeFirstDbContext))]
    [Migration("20251209164714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("K2TeamProjectNEW.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassroomID"));

                    b.Property<string>("ClassroomName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ClassroomID");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            ClassroomID = 1,
                            ClassroomName = "A101"
                        },
                        new
                        {
                            ClassroomID = 2,
                            ClassroomName = "B205"
                        },
                        new
                        {
                            ClassroomID = 3,
                            ClassroomName = "C303"
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<DateOnly?>("CourseEndDate")
                        .HasColumnType("date");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CourseStartDate")
                        .HasColumnType("date");

                    b.Property<int?>("FkTeacherTeacherID")
                        .HasColumnType("int");

                    b.Property<int?>("Fk_TeacherID")
                        .HasColumnType("int");

                    b.HasKey("CourseID");

                    b.HasIndex("FkTeacherTeacherID");

                    b.ToTable("Course", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("FkCourseID")
                        .HasColumnType("int");

                    b.Property<int>("FkGradeID")
                        .HasColumnType("int");

                    b.Property<int>("FkStudentID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasMaxLength(150)
                        .HasColumnType("date");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("FkCourseID");

                    b.HasIndex("FkGradeID");

                    b.HasIndex("FkStudentID");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentID = 1,
                            FkCourseID = 1,
                            FkGradeID = 1,
                            FkStudentID = 1,
                            RegistrationDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            EnrollmentID = 2,
                            FkCourseID = 2,
                            FkGradeID = 2,
                            FkStudentID = 1,
                            RegistrationDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            EnrollmentID = 3,
                            FkCourseID = 2,
                            FkGradeID = 3,
                            FkStudentID = 2,
                            RegistrationDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            EnrollmentID = 4,
                            FkCourseID = 2,
                            FkGradeID = 4,
                            FkStudentID = 2,
                            RegistrationDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            EnrollmentID = 5,
                            FkCourseID = 1,
                            FkGradeID = 5,
                            FkStudentID = 3,
                            RegistrationDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            EnrollmentID = 6,
                            FkCourseID = 1,
                            FkGradeID = 6,
                            FkStudentID = 4,
                            RegistrationDate = new DateOnly(2025, 9, 1)
                        },
                        new
                        {
                            EnrollmentID = 7,
                            FkCourseID = 2,
                            FkGradeID = 6,
                            FkStudentID = 4,
                            RegistrationDate = new DateOnly(2026, 1, 7)
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeID"));

                    b.Property<int>("FkStudentID")
                        .HasColumnType("int");

                    b.Property<int>("FkTeacherID")
                        .HasColumnType("int");

                    b.Property<string>("GradeScale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("GradedDate")
                        .HasMaxLength(150)
                        .HasColumnType("date");

                    b.HasKey("GradeID");

                    b.HasIndex("FkStudentID");

                    b.HasIndex("FkTeacherID");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeID = 1,
                            FkStudentID = 1,
                            FkTeacherID = 1,
                            GradeScale = "A",
                            GradedDate = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            GradeID = 2,
                            FkStudentID = 1,
                            FkTeacherID = 2,
                            GradeScale = "B+",
                            GradedDate = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            GradeID = 3,
                            FkStudentID = 2,
                            FkTeacherID = 2,
                            GradeScale = "A-",
                            GradedDate = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            GradeID = 4,
                            FkStudentID = 2,
                            FkTeacherID = 3,
                            GradeScale = "C",
                            GradedDate = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            GradeID = 5,
                            FkStudentID = 3,
                            FkTeacherID = 1,
                            GradeScale = "B",
                            GradedDate = new DateOnly(2025, 12, 18)
                        },
                        new
                        {
                            GradeID = 6,
                            FkStudentID = 1,
                            FkTeacherID = 1,
                            GradeScale = "Pending",
                            GradedDate = new DateOnly(2025, 9, 1)
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Scheduling", b =>
                {
                    b.Property<int>("SchedulingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchedulingID"));

                    b.Property<int>("FkClassroomID")
                        .HasColumnType("int");

                    b.Property<int>("FkCourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SchedulingEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SchedulingStartDateTime")
                        .HasMaxLength(150)
                        .HasColumnType("datetime2");

                    b.HasKey("SchedulingID");

                    b.HasIndex("FkClassroomID");

                    b.HasIndex("FkCourseID");

                    b.ToTable("Schedulings");

                    b.HasData(
                        new
                        {
                            SchedulingID = 1,
                            FkClassroomID = 1,
                            FkCourseID = 1,
                            SchedulingEndDateTime = new DateTime(2025, 9, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SchedulingStartDateTime = new DateTime(2025, 9, 8, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SchedulingID = 2,
                            FkClassroomID = 2,
                            FkCourseID = 2,
                            SchedulingEndDateTime = new DateTime(2025, 9, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SchedulingStartDateTime = new DateTime(2025, 9, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SchedulingID = 3,
                            FkClassroomID = 3,
                            FkCourseID = 2,
                            SchedulingEndDateTime = new DateTime(2025, 9, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SchedulingStartDateTime = new DateTime(2025, 9, 8, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SchedulingID = 4,
                            FkClassroomID = 1,
                            FkCourseID = 1,
                            SchedulingEndDateTime = new DateTime(2025, 9, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SchedulingStartDateTime = new DateTime(2025, 9, 10, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SchedulingID = 5,
                            FkClassroomID = 1,
                            FkCourseID = 2,
                            SchedulingEndDateTime = new DateTime(2026, 1, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            SchedulingStartDateTime = new DateTime(2026, 1, 14, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            StudentFirstName = "Alice",
                            StudentLastName = "Johnson"
                        },
                        new
                        {
                            StudentID = 2,
                            StudentFirstName = "Bob",
                            StudentLastName = "Williams"
                        },
                        new
                        {
                            StudentID = 3,
                            StudentFirstName = "Charlie",
                            StudentLastName = "Brown"
                        },
                        new
                        {
                            StudentID = 4,
                            StudentFirstName = "Diana",
                            StudentLastName = "Smith"
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teacher", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Course", b =>
                {
                    b.HasOne("K2TeamProjectNEW.Models.Teacher", "FkTeacher")
                        .WithMany("Courses")
                        .HasForeignKey("FkTeacherTeacherID");

                    b.Navigation("FkTeacher");
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Enrollment", b =>
                {
                    b.HasOne("K2TeamProjectNEW.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("FkCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2TeamProjectNEW.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("FkGradeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("K2TeamProjectNEW.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("FkStudentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Grade");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Grade", b =>
                {
                    b.HasOne("K2TeamProjectNEW.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("FkStudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2TeamProjectNEW.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("FkTeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Scheduling", b =>
                {
                    b.HasOne("K2TeamProjectNEW.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("FkClassroomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("K2TeamProjectNEW.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("FkCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
