// <auto-generated />
using System;
using K2TeamProjectNEW.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace K2TeamProjectNEW.Migrations
{
    [DbContext(typeof(K2TeamProjectDbContext))]
    partial class K2TeamProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("K2TeamProjectNEW.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateOnly?>("CourseEndDate")
                        .HasColumnType("date");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("CourseStartDate")
                        .HasColumnType("date");

                    b.Property<int?>("Fk_TeacherID")
                        .HasColumnType("int")
                        .HasColumnName("Fk_TeacherID");

                    b.HasKey("CourseID")
                        .HasName("PK__Course__C92D71879A78CCFE");

                    b.HasIndex("Fk_TeacherID");

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseEndDate = new DateOnly(2025, 12, 19),
                            CourseName = "Engelska 1",
                            CourseStartDate = new DateOnly(2025, 12, 18),
                            Fk_TeacherID = 1
                        },
                        new
                        {
                            CourseID = 2,
                            CourseEndDate = new DateOnly(2025, 12, 21),
                            CourseName = "Engelska 2",
                            CourseStartDate = new DateOnly(2025, 12, 20),
                            Fk_TeacherID = 1
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherID")
                        .HasName("PK__Teacher__EDF259440181DB12");

                    b.ToTable("Teacher", (string)null);

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            TeacherName = "Markus Silva"
                        },
                        new
                        {
                            TeacherID = 2,
                            TeacherName = "Jenny Larsson"
                        },
                        new
                        {
                            TeacherID = 3,
                            TeacherName = "Henrik Andersson"
                        });
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Course", b =>
                {
                    b.HasOne("K2TeamProjectNEW.Models.Teacher", "FkTeacher")
                        .WithMany("Courses")
                        .HasForeignKey("Fk_TeacherID")
                        .HasConstraintName("FK__Course__Fk_Teach__398D8EEE");

                    b.Navigation("FkTeacher");
                });

            modelBuilder.Entity("K2TeamProjectNEW.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
